"""
Build a double-clickable macOS app, "Lunoviq FPA.app", with its own icon.

The app starts the local web server in the background (no Terminal window)
if it is not already running, waits for it, and opens the browser. The server
keeps running until "Quit" is chosen in the web app or the Mac restarts.
Log: ~/Library/Logs/LunoviqFPA.log

Usage:
    python tools/make_mac_app.py [--dest ~/Applications]
"""
import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PORT = 8766

LAUNCHER = """#!/bin/bash
# Lunoviq FPA.app launcher (generated by tools/make_mac_app.py)
PROJECT="{project}"
PY="{python}"
URL="http://127.0.0.1:{port}"
LOG="$HOME/Library/Logs/LunoviqFPA.log"

if ! /usr/bin/curl -s -o /dev/null -m 2 "$URL/api/state"; then
  if [ ! -d "$PROJECT" ]; then
    /usr/bin/osascript -e 'display alert "Lunoviq FP&A" message "Project folder not found: {project}. Rebuild the app with tools/make_mac_app.py."'
    exit 1
  fi
  cd "$PROJECT" || exit 1
  echo "--- start $(date)" >> "$LOG"
  nohup "$PY" -W ignore -m fpa serve --no-browser --port {port} >> "$LOG" 2>&1 &
  for i in $(seq 1 60); do
    /usr/bin/curl -s -o /dev/null -m 1 "$URL/" && break
    sleep 0.5
  done
fi
/usr/bin/open "$URL"
"""

PLIST = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>Lunoviq FPA</string>
  <key>CFBundleDisplayName</key><string>Lunoviq FP&amp;A</string>
  <key>CFBundleIdentifier</key><string>com.lunoviq.fpa</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>LunoviqFPA</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSAppleEventsUsageDescription</key><string>Lunoviq FP&amp;A uses Microsoft Excel to recalculate the management pack.</string>
</dict></plist>
"""


def draw_icon(path, size=1024):
    """Brand mark: navy rounded square, light-blue lower-right triangle, white bar chart."""
    from PIL import Image, ImageDraw
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    pad, r = int(size * 0.09), int(size * 0.2)
    box = (pad, pad, size - pad, size - pad)
    d.rounded_rectangle(box, r, fill=(31, 95, 139, 255))
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).rounded_rectangle(box, r, fill=255)
    tri = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    ImageDraw.Draw(tri).polygon([(size - pad, pad), (size - pad, size - pad), (pad, size - pad)],
                                fill=(169, 199, 221, 255))
    img.paste(tri, (0, 0), Image.composite(tri.split()[3], Image.new("L", (size, size), 0), mask))
    # budget (dashed) and actual/forecast line
    pts = [(0.24, 0.66), (0.38, 0.52), (0.52, 0.58), (0.66, 0.40), (0.78, 0.30)]
    xy = [(int(size * x), int(size * y)) for x, y in pts]
    d.line(xy, fill=(255, 255, 255, 255), width=int(size * 0.045), joint="curve")
    for x, y in xy:
        r = int(size * 0.035)
        d.ellipse((x - r, y - r, x + r, y + r), fill=(255, 255, 255, 255))
    base = int(size * 0.74)
    d.rounded_rectangle((int(size * 0.2), base, int(size * 0.82), base + int(size * 0.03)), int(size * 0.015),
                        fill=(255, 255, 255, 170))
    img.save(path)


def build(dest):
    dest = Path(os.path.expanduser(dest))
    app = dest / "Lunoviq FPA.app"
    if app.exists():
        shutil.rmtree(app)
    (app / "Contents" / "MacOS").mkdir(parents=True)
    (app / "Contents" / "Resources").mkdir()
    (app / "Contents" / "Info.plist").write_text(PLIST)
    exe = app / "Contents" / "MacOS" / "LunoviqFPA"
    python = "/opt/anaconda3/bin/python3" if Path("/opt/anaconda3/bin/python3").exists() else sys.executable
    exe.write_text(LAUNCHER.format(project=ROOT, python=python, port=PORT))
    exe.chmod(0o755)

    with tempfile.TemporaryDirectory() as tmp:
        png = Path(tmp) / "icon.png"
        draw_icon(png)
        iconset = Path(tmp) / "AppIcon.iconset"
        iconset.mkdir()
        for s in (16, 32, 128, 256, 512):
            for scale in (1, 2):
                name = "icon_%dx%d%s.png" % (s, s, "@2x" if scale == 2 else "")
                subprocess.run(["sips", "-z", str(s * scale), str(s * scale), str(png),
                                "--out", str(iconset / name)], check=True, capture_output=True)
        subprocess.run(["iconutil", "-c", "icns", str(iconset),
                        "-o", str(app / "Contents" / "Resources" / "AppIcon.icns")], check=True)
        shutil.copy(png, ROOT / "docs" / "lunoviq_fpa_icon.png")
    subprocess.run(["touch", str(app)], check=False)          # refresh Finder's icon cache
    print("Built", app)
    return app


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--dest", default="~/Applications")
    build(ap.parse_args().dest)
